name: GitOps Demo CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Install and Test
        run: |
          pip install build
          pip install .[test]
          pytest

  build-image:
    needs: test
    runs-on: ubuntu-latest
    # Map step outputs to job outputs so the next job can see them
    outputs:
      sha: ${{ steps.meta.outputs.sha }}
      environment: ${{ steps.meta.outputs.environment }}
      version: ${{ steps.meta.outputs.version }}
      is_release: ${{ steps.meta.outputs.is_release }}
    steps:
      - uses: actions/checkout@v5
      - name: Generate Metadata
        id: meta
        run: |
          SHA=${GITHUB_SHA::8}
          echo "sha=${SHA}" >> $GITHUB_OUTPUT
          
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
            echo "environment=production" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "is_release=false" >> $GITHUB_OUTPUT
            echo "environment=production" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
            echo "is_release=false" >> $GITHUB_OUTPUT
            echo "environment=staging" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
            echo "environment=none" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN}}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # create several tags, always push the commit SHA and push others conditionally (develop, latest, version)
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/gitops-demo-service:${{ steps.meta.outputs.sha }}
            ${{ steps.meta.outputs.is_release == 'true' && format('{0}/gitops-demo-service:{1}', secrets.DOCKER_USERNAME, steps.meta.outputs.version) || '' }}
            ${{ github.ref == 'refs/heads/main' && format('{0}/gitops-demo-service:latest', secrets.DOCKER_USERNAME) || '' }}
            ${{ github.ref == 'refs/heads/develop' && format('{0}/gitops-demo-service:develop', secrets.DOCKER_USERNAME) || '' }}

  update-config-repo:
    needs: build-image
    if: needs.build-image.outputs.environment != 'none'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config Repo
        uses: actions/checkout@v5
        with:
          repository: '${{ github.repository_owner }}/gitops-demo-config'
          token: '${{ secrets.K8S_GITHUB_PAT }}'
          path: gitops-demo-config

      - name: Update Version File
        run: |
          cd gitops-demo-config
          
          # setup bot identity
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          ENV_PATH="environments/${{ needs.build-image.outputs.environment }}"
          mkdir -p "$ENV_PATH"
          
          # 1. Determine which version string to use
          if [ "${{ needs.build-image.outputs.is_release }}" = "true" ]; then
            # If it's a tag (vx.x.x), use the tag name
            TAG_TO_USE="${{ needs.build-image.outputs.version }}"
          elif [ "${{ github.ref }}" = "refs/heads/main" ]; then
            # If it's the main branch, use 'latest'
            TAG_TO_USE="latest"
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            # If it's the develop branch, use 'develop'
            TAG_TO_USE="develop"
          else
            # Fallback to the specific commit SHA
            TAG_TO_USE="${{ needs.build-image.outputs.sha }}"
          fi
          
          # 2. Create/update version file for GitOps using specified tag from above
          echo "/gitops-demo-service:${TAG_TO_USE}" > ${ENV_PATH}/gitops-demo-service.version
          echo "/gitops-demo-service:${{ needs.build-image.outputs.sha }}" > environments/test/gitops-demo-service.version
          
          git add .
          git commit -m "Update gitops-demo-service to ${TAG_TO_USE}} in ${{ needs.build-image.outputs.environment }}"
          git push
      
